# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool: Patika
  

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build' 
      projects: './backend' 
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'  
      projects: './backend'  
      arguments: '--configuration Release --output C:\Users\erene\OneDrive\Masa端st端\PatikaPublish' 
      zipAfterPublish: false
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhuberen'
      repository: 'erenengin/backend'
      command: 'build'
      Dockerfile: '.\backend\dockerfile-pipeline'
      buildContext: 'C:\Users\erene\OneDrive\Masa端st端\PatikaPublish\backend'

