# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool: Patika
  

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build' 
      projects: '**/*.csproj' 
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'  # Proje yayınlama görevi
      projects: '**/*.csproj'  # Proje dosyalarının yolunu belirtin
      publishWebProjects: false  # Eğer bir web projesi değilse false olarak ayarlayın
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'  # Yayınlama yapılandırmasını ve çıktı dizinini belirtin


